name: 自动签到续费麦块联机

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *' #没见过这么der的网站 4点运行会报错502
  workflow_dispatch:

jobs:
  read-and-access:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 签到续费麦块联机
      env:
        MK_USERPASSWD: ${{ secrets.MK_USERPASSWD }}
      run: |
        # 分割 MK_USERPASSWD 并按逗号解析为数组
        IFS=',' read -r -a entries <<< "$MK_USERPASSWD"

        # 遍历每一组 user_id:server_id:prices 数据
        for entry in "${entries[@]}"; do
          IFS=':' read -r user_id server_id prices <<< "$entry"

          echo "正在处理用户 ID: $user_id, 服务器 ID: $server_id, 价格: $prices"

          # 签到请求
          response=$(curl -s 'https://api.ungc.com.cn/api/minekuai/points/signIn' \
            -H 'content-type: application/json' \
            --data "${user_id}")

          if echo "$response" | grep -q '"code":1'; then
            echo "签到成功"
          else
            echo "签到失败，内容返回: $response"
          fi

          # 续费请求
          response=$(curl -s 'https://api.ungc.com.cn/api/minekuai/modifyServerSuspendTime/' \
            -H 'content-type: application/json' \
            --data "{\"user_id\":${user_id},\"server_id\":${server_id},\"days\":1,\"prices\":${prices}}")

          if echo "$response" | grep -q '"code":1'; then
            echo "续费成功"
          else
            echo "续费失败，内容返回: $response"
          fi
        done
