name: 自动签到续费麦块联机

on:
  schedule:
    - cron: '0 4 * * *' # 每天 4 点运行
  workflow_dispatch:

jobs:
  read-and-access:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 签到续费麦块联机
      env:
        MK_TOKENS: ${{ secrets.MK_TOKENS }}
        MK_CLIENTID: ${{ secrets.MK_CLIENTID }}
      run: |
        #!/bin/bash
        set -e

        IFS=',' read -r -a entries <<< "$MK_TOKENS"

        for entry in "${entries[@]}"; do
          IFS=':' read -r playload encryptkey server <<< "$entry"

          echo "正在尝试登录..."
          login_response=$(curl -s 'https://api.minekuai.com/auth/pterodactylLogin' \
            -H "accept: application/json, text/plain, */*" \
            -H "clientid: $MK_CLIENTID" \
            -H "content-language: zh_CN" \
            -H "content-type: application/json;charset=UTF-8" \
            -H "encrypt-key: $encryptkey" \
            -H "isencrypt: true" \
            -H "istoken: false" \
            -H "origin: https://minekuai.com" \
            -H "user-agent: Mozilla/5.0" \
            --data-raw "$playload")

          access_token=$(echo "$login_response" | jq -r '.data.access_token')
          msg_login=$(echo "$login_response" | jq -r '.msg')

          if [[ "$access_token" == "null" || -z "$access_token" ]]; then
            echo "❌ 登录失败：$msg_login"
            continue
          fi

          echo "✅ 登录成功，开始签到..."

          sign_response=$(curl -s 'https://api.minekuai.com/system/sign' \
            -H "authorization: Bearer $access_token" \
            -H "clientid: $MK_CLIENTID" \
            -H "content-language: zh_CN" \
            -H "origin: https://minekuai.com" \
            -H "user-agent: Mozilla/5.0")

          msg_sign=$(echo "$sign_response" | jq -r '.msg')
          echo "📌 签到结果：$msg_sign"

          echo "正在尝试续费服务器"

          renew_response=$(curl -s -X POST "https://api.minekuai.com/system/mineKuaiSystem/reNewInstance?serverId=$server&days=1" \
            -H "authorization: Bearer $access_token" \
            -H "clientid: $MK_CLIENTID" \
            -H "content-language: zh_CN" \
            -H "origin: https://minekuai.com" \
            -H "user-agent: Mozilla/5.0")

          msg_renew=$(echo "$renew_response" | jq -r '.msg')
          echo "🔄 续费结果：$msg_renew"

          echo "处理完成 ✅"
          echo "---------------------------------------"
        done
